- name: Scan Start
        id: start
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN}}
          hostname: app.neuralegion.com
          name: Bright Scan - ${{ github.sha }}
          restart_scan: $SCAN_ID
